package-lock.json
package.json
src/App.test.js
src/components/executeRequest/executeRequest.jsx
src/components/factsheet/duck.js
src/components/factsheet/factsheet.jsx
src/components/factsheet/middleware.js
src/components/managerView/managerView.jsx
src/components/orderbook/middleware.js
src/components/participation/participation.jsx
src/components/recentTrades/middleware.js
src/components/settings/settings.jsx
src/components/setup/duck.js
src/components/setup/middleware.js
src/components/setup/setup.jsx
src/components/statistics/statistics.jsx
src/components/trade/container.js
src/components/tradeHelper/container.js
src/components/tradeHelper/duck.js
src/components/tradeHelper/tradeHelper.jsx
src/components/tradingActivity/middleware.js
src/index.js

Fix #20 #21 #37 #26 #28 #29 #30 #37 #19

Fix issues

---

src/components/app/App.jsx
src/components/app/LockedAccount.jsx
src/components/app/NoMetamask.jsx
src/components/app/WrongNetwork.jsx
src/components/generalMiddleware.js
src/components/web3/duck.js
src/components/web3/middleware.js
src/index.js

First version of error messages. Will need some refactoring.

Fix web3 connection

---

src/actions/app.js
src/components/pages/App.jsx
src/containers/App.js
src/containers/Fund.js
src/reducers/app.js
src/sagas/app.js
src/sagas/index.js

You can delete this branch afterwards

Refactored onboardingState

---

package-lock.json
package.json
src/sagas/participation.js
src/sagas/setup.js

Pass wallet as first argument always. Update to melon.js v0.5.0-alpha.18

---

src/actions/app.js
src/actions/orderbook.js
src/actions/recentTrades.js
src/actions/tradeHelper.js
src/components/organisms/TradeHelper.jsx
src/containers/Holdings.js
src/containers/Orderbook.js
src/containers/RecentTrades.js
src/containers/TradeHelper.js
src/reducers/app.js
src/reducers/tradeHelper.js
src/sagas/app.js
src/sagas/index.js
src/sagas/orderbook.js
src/sagas/recentTrades.js
src/sagas/tradeHelper.js

Trade helper

---

cypress/fixtures/example.json
cypress/fixtures/walletReadyToTrade.json
cypress/integration/administration.js
cypress/integration/walkthrough.js
package-lock.json
package.json
src/actions/administration.js
src/actions/orderbook.js
src/actions/trade.js
src/components/organisms/Orderbook.jsx
src/components/organisms/Trade.jsx
src/components/pages/Fund.jsx
src/components/utils/renderInput.jsx
src/containers/Administration.js
src/containers/Orderbook.js
src/containers/Trade.js
src/reducers/fund.js
src/reducers/orderbook.js
src/sagas/administration.js
src/sagas/ethereum.js
src/sagas/index.js
src/sagas/orderbook.js
src/sagas/trade.js
src/utils/functionalBigNumber.js

- e2e tests for fund administration
- Fund administration sagas to use new dialog
- Set defaultAccount on melon.js setup to a checksummed one

Fund administration

---

package-lock.json
package.json
src/actions/orderbook.js
src/actions/trade.js
src/components/organisms/Holdings.jsx
src/components/organisms/Orderbook.jsx
src/components/organisms/Trade.jsx
src/components/pages/Fund.jsx
src/components/utils/renderInput.jsx
src/containers/Orderbook.js
src/containers/Trade.js
src/reducers/orderbook.js
src/sagas/index.js
src/sagas/orderbook.js
src/sagas/trade.js
src/utils/functionalBigNumber.js

Trade form

---

package-lock.json
package.json
src/actions/trade.js
src/components/organisms/Trade.jsx
src/components/organisms/TradeHelper.jsx
src/containers/Trade.js
src/containers/TradeHelper.js
src/sagas/trade.js

Trading modals

---

src/actions/fund.js
src/containers/Factsheet.js
src/containers/RecentTrades.js
src/containers/TradeHistory.js
src/reducers/fund.js
src/sagas/fund.js

- Fix dates in factsheet recent trades and trade history

Fix dates for factsheet, recent trades and trade history

---

package-lock.json
package.json
src/actions/ethereum.js
src/components/organisms/ConnectionInfo.jsx
src/components/organisms/ConnectionInfo.story.jsx
src/components/pages/App.jsx
src/containers/App.js
src/reducers/ethereum.js
src/sagas/ethereum.js

- Small sticky status indicator on the top right about the account, balances and status

Small info

---

src/components/organisms/Holdings.jsx
src/components/organisms/Orderbook.jsx
src/containers/Holdings.js
src/containers/Orderbook.js
src/sagas/app.js

Visitor mode patches

---

src/components/molecules/NumberInput.jsx
src/components/molecules/NumberInput.story.jsx
src/components/organisms/ParticipationForm.jsx
src/components/organisms/Trade.jsx
src/components/utils/renderInput.jsx
src/sagas/fund.js

- Intelligent number input component that is decimal aware

Intelligent number input component

---

src/actions/account.js
src/actions/routes.js
src/components/organisms/ConnectionInfo.jsx
src/components/organisms/MyAccount.jsx
src/components/pages/App.jsx
src/containers/Account.js
src/containers/MyAccount.js
src/sagas/account.js
src/sagas/participation.js

More patches

---

package-lock.json
package.json
src/sagas/administration.js
src/utils/functionalBigNumber.js

- Functional BigNumber to know how to handle "..."
- Shutdown fund #161

Fix shut down fund. Closes #161

---

.snyk
package-lock.json
package.json

add snyk (security)

---

.snyk
package-lock.json
package.json
src/components/molecules/MaybeData.jsx
src/components/organisms/Factsheet.jsx
src/components/organisms/Holdings.jsx
src/components/organisms/ParticipationForm.jsx
src/components/organisms/Trade.jsx
src/components/pages/Fund.jsx
src/containers/Factsheet.js
src/containers/Holdings.js
src/containers/Participation.js
src/containers/Trade.js
src/reducers/ethereum.js
src/sagas/app.js

- MaybeData component to mark data as red if datafeed is down
- Change forms depending on data feed to disable if down

Disable forms pricefeed

---

package-lock.json
package.json
src/actions/openOrders.js
src/components/organisms/OpenOrders.jsx
src/components/pages/Fund.jsx
src/containers/OpenOrders.js
src/reducers/index.js
src/reducers/openOrders.js
src/sagas/fund.js
src/sagas/index.js
src/sagas/openOrders.js

- Open orders table
- Option to cancel order
- Closes #93

Open orders

---

package-lock.json
package.json
src/actions/openOrders.js
src/components/organisms/Factsheet.jsx
src/components/organisms/OpenOrders.jsx
src/components/organisms/ParticipationForm.jsx
src/components/pages/Ranking.jsx
src/containers/OpenOrders.js
src/sagas/fund.js
src/sagas/openOrders.js

- [Label change] Invest -> Redeem
- Melon.js version bump 0.6.22
- cancel order in open orders table 
- Closes #178

Fix cancel order in open orders table

---

src/sagas/ranking.js

Fetch ranking from ranking.melon.fund

Fetch ranking from ranking.melon.fund

---

src/actions/fund.js
src/components/organisms/TermsAndConditions.jsx
src/components/pages/App.jsx
src/containers/TermsAndConditions.js
src/reducers/app.js
src/reducers/fund.js
src/sagas/app.js
src/sagas/setup.js

- TermsAndConditions component
- Adjust setup saga

Sign terms and conditions

---

src/components/organisms/Factsheet.jsx
src/components/organisms/InsufficientFunds.jsx
src/components/organisms/ParticipationForm.jsx
src/components/organisms/Setup.jsx
src/components/organisms/account/Generate.jsx

Fix typos; make sure we show its test tokens everywhere

---

src/containers/Ranking.js

- Fix bug in sorting by sharePrice. addresses #180

Fix sorting by share price. Addresses #180

---

package-lock.json
package.json
src/components/molecules/NumberInput.jsx
src/components/organisms/GetStarted.jsx
src/components/organisms/TermsAndConditions.jsx
src/containers/Trade.js
src/index.js
src/sagas/orderbook.js
src/sagas/setup.js
src/utils/functionalBigNumber.js

- Hiring message in console.log
- Cap quantity/total to holdings for market orders
- Tracking information
- #174 
- Prevent same names more restrictive in the frontend. #202 (Not fixed yet, we need to investigate on the protocol why this was even possible)

Bugs & improvements

---

src/actions/ethereum.js
src/reducers/ethereum.js
src/reducers/ethereum.test.js
src/sagas/ethereum.js

- Cleaner block polling. Show error if connection error to node.
- #212

Cleaner block polling. Fixes #212

---

package-lock.json
package.json
src/actions/fund.js
src/components/organisms/Administration.jsx
src/components/organisms/Factsheet.jsx
src/components/pages/Ranking.jsx
src/containers/Administration.js
src/containers/Factsheet.js
src/index.js
src/reducers/fund.js
src/sagas/app.js
src/sagas/fund.js
src/sagas/ranking.js

- Expected prize for competing funds on ranking page and fund page

Add expected prize on ranking and fund page

---

.babelrc
package-lock.json
package.json
src/components/organisms/ExecuteRequest.jsx
src/components/organisms/Holdings.jsx
src/components/organisms/InsufficientFunds.jsx
src/components/organisms/LockedAccount.jsx
src/components/organisms/MyAccount.jsx
src/components/organisms/OpenOrders.jsx
src/components/organisms/RecentTrades.jsx
src/components/organisms/TradeHistory.jsx
src/containers/CompetitionRegistration.js
src/containers/Fund.js
src/containers/Orderbook.js
src/containers/Restore.js
src/containers/TermsAndConditions.js
src/index.js
src/sagas/app.js
src/sagas/fund.js
src/sagas/tracker.js
src/sagas/trade.js
src/utils/serialize.js

- Some eslint fixes
- Refactor Object.values, Object.entries into ES5 safe commands

Fix mobile

---

src/containers/App.js
src/sagas/administration.js
src/sagas/ethereum.js
src/sagas/fund.js
src/sagas/holdings.js
src/sagas/openOrders.js
src/sagas/orderbook.js
src/sagas/participation.js
src/sagas/recentTrades.js
src/sagas/setup.js
src/sagas/signer.js
src/sagas/trade.js
src/sagas/tradeHistory.js

* Call all blockchain functions with an environment

Environment

---

package-lock.json
package.json
public/manifest.json
src/sagas/ethereum.js

* Scripts to deploy to Github Pages to pin from Parity
* Update to latest melon.js version

Parity deploy

---

package-lock.json
package.json
src/components/organisms/Holdings.jsx
src/components/organisms/InsufficientFunds.jsx
src/components/pages/App.jsx
src/containers/App.js
src/sagas/app.js
src/sagas/ethereum.js
src/sagas/ranking.js

Live prep2

---

package-lock.json
package.json

Melon.js version bump

---

package-lock.json
package.json
src/actions/fund.js
src/actions/participation.js
src/components/organisms/Administration.jsx
src/components/organisms/ConnectionInfo.jsx
src/components/organisms/Factsheet.jsx
src/components/organisms/GetStarted.jsx
src/components/organisms/MyAccount.jsx
src/components/organisms/NoConnection.jsx
src/components/organisms/ParticipationForm.jsx
src/components/organisms/Setup.jsx
src/components/organisms/TermsAndConditions.jsx
src/components/pages/App.jsx
src/components/pages/Ranking.jsx
src/containers/Administration.js
src/containers/App.js
src/containers/Factsheet.js
src/containers/GetStarted.js
src/containers/MyAccount.js
src/containers/Participation.js
src/containers/Setup.js
src/containers/TermsAndConditions.js
src/reducers/fund.js
src/sagas/account.js
src/sagas/ethereum.js
src/sagas/fund.js
src/sagas/participation.js
src/sagas/ranking.js
src/sagas/setup.js

* Redeem in slices
* Network name in connection info 
* Dynamic symbols according to network used 
* Dynamic T&Cs according to network used 
* Dynamic links according to network used 
* Competition Registration
* #247 
* #243 
* #239 
* #246 
* #241

Pre launch

---

package-lock.json
package.json
src/components/organisms/ExecuteRequest.jsx
src/components/pages/Ranking.jsx
src/containers/ExecuteRequest.js
src/sagas/fund.js
src/sagas/participation.js
src/sagas/ranking.js

* Gets request execution timeout from chain

Execution timeout from chain

---

package-lock.json
package.json
src/components/organisms/ExecuteRequest.jsx
src/components/organisms/GetStarted.jsx
src/components/pages/Ranking.jsx
src/containers/ExecuteRequest.js
src/sagas/fund.js
src/sagas/participation.js
src/sagas/ranking.js

Merges to master because I deployed. You can merge to develop also.

Upgrade melonjs

---

package-lock.json
package.json

update to melon.js@0.7.6

---

src/components/organisms/Administration.jsx
src/components/organisms/Orderbook.jsx
src/sagas/fund.js
src/sagas/participation.js
src/sagas/ranking.js
src/sagas/setup.js

- First investment bug
- Missing rank on ranking page
- Fix cumulative volume on orderbook
- Fix bug after fund creation that was redirecting to fund's page instead of invest (participation)

First investment bug fix
